#
# This is a generated file.
#

api.version=v1.0
openapi.resource=true
openapi.resource.path=/sample-rest-builder
osgi.jaxrs.application.select=(osgi.jaxrs.name=SampleRestBuilder)
osgi.jaxrs.resource=true